name: Automated Web Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy Container
    runs-on: ubuntu-latest

    steps:
      
      - name: Fetch Codebase
        uses: actions/checkout@v4

      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

     
      - name: Build, Tag, and Push Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: node-web-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build ECR image with unique commit SHA and latest tags
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          # Push image layers to AWS ECR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          # Output the image URI to be used in the next step
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
        id: build-image

      
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs-task.json
          container-name: node-container
          image: ${{ steps.build-image.outputs.image }}

      
      - name: Deploy to Amazon ECS Service
        uses: aws-actions/amazon-ecs-deploy-task-def@v1
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: node-app-service
          cluster: devops-cluster
          wait-for-service-stability: true
